Use Case
You are provided with a dataset from a bank that contains customer demographic and financial information. Your task is to perform a series of data cleaning and preprocessing steps to prepare the data for further analysis or modeling. You'll handle missing values, standardize column names, and handle outliers.


Problem Description
Implement the notebook cells to perform the following tasks:

Implement a series of cells that:

✅ Step 1: Load the Dataset

Read the dataset (bank_data.csv) using pandas.

The dataset URL: https://gitlab.crio.do/me_notebook/me_jupyter_bankattritionanalysis/-/raw/master/bank_attrition_dataset.csv

Skip the metadata row from the dataset.

Display the first few rows to get an overview.

📌 Hint: Use pd.read_csv() and .head().

In [3]:
import pandas as pd
import numpy as np

In [4]:
# using url to load data 
url = "https://gitlab.crio.do/me_notebook/me_jupyter_bankattritionanalysis/-/raw/master/bank_attrition_dataset.csv"
df = pd.read_csv(url,skiprows=[1])
df.head
# df.tail # we can use it for

<bound method NDFrame.head of        RowNumber CustomerId first_name        state  Gender  Age  Tenure  \
0              1    TN00001     Sunita   Tamil Nadu  Female   26       1
1              2    MH00002      Rohan  Maharashtra    Male   54       4
2              3    KA00003     Ananya    Karnataka  Female   58       1
3              4    MH00004    Nandini  Maharashtra  Female   39       2
4              5    WB00005     Charvi  West Bengal  Female   25       3
...          ...        ...        ...          ...     ...  ...     ...
14995      14996    KA14996  Vaishnavi    Karnataka  Female   25       3
14996      14997    MH14997     Varsha  Maharashtra  Female   49       2
14997      14998    KA14998     Deepak    Karnataka    Male   69       2
14998      14999    WB14999    Anirudh  West Bengal    Male   53       8
14999      15000    DL15000     Jhanvi        Delhi  Female   42       6

       CreditScore    Balance  HasCrCard  ... HasFD  NumOfProducts  \
0              673  117822.37          1  ...     1              2
1              600  163508.11          1  ...     1              3
2              724  138773.12          1  ...     1              3
3              695  136048.53          1  ...     0              1
4              675   27798.19          0  ...     0              0
...            ...        ...        ...  ...   ...            ...
14995          669       0.00          1  ...     1              3
14996          768  193069.04          1  ...     0              2
14997          600       0.00          1  ...     0              1
14998          793  100747.75          0  ...     0              1
14999          663   10280.30          1  ...     0              1

       IsActiveMember    Salary  Exited  Complain  NumComplain  \
0                   1   62000.0       0         0            0
1                   1   62000.0       0         0            0
2                   1   97000.0       0         0            0
3                   1  157000.0       0         0            0
4                   1  146000.0       0         0            0
...               ...       ...     ...       ...          ...
14995               1  138000.0       0         0            0
14996               1   76000.0       0         1            2
14997               0   74000.0       1         1            9
14998               1  120000.0       0         1           19
14999               1  147000.0       0         0            0

       Satisfaction Score  Point Earned  PreferredChannel
0                     5.0           100            Mobile
1                    10.0           150            Mobile
2                     5.0           100            Mobile
3                    10.0           150             Email
4                     6.0           110            Mobile
...                   ...           ...               ...
14995                 6.0           110             Email
14996                 4.0            90            Branch
14997                 3.0            12            Branch
14998                 4.0             2            Mobile
14999                 7.0           120             Phone

[15000 rows x 22 columns]>

✅ Step 2: Check Column Headers

Print the column names of the dataset.

Standardize the column names: convert to lowercase and replace spaces with underscores.

📌 Hint: Use .str.lower() and .str.replace() on df.columns.

In [8]:
df.columns #for columns we know

Index(['rownumber', 'customerid', 'first_name', 'state', 'gender', 'age',
       'tenure', 'creditscore', 'balance', 'hascrcard', 'card type', 'hasloan',
       'hasfd', 'numofproducts', 'isactivemember', 'salary', 'exited',
       'complain', 'numcomplain', 'satisfaction score', 'point earned',
       'preferredchannel'],
      dtype='object')

In [10]:
df.columns = df.columns.str.lower()
df

,rownumber,customerid,first_name,state,gender,age,tenure,creditscore,balance,hascrcard,...,hasfd,numofproducts,isactivemember,salary,exited,complain,numcomplain,satisfaction score,point earned,preferredchannel
0,1,TN00001,Sunita,Tamil Nadu,Female,26,1,673,117822.37,1,...,1,2,1,62000.0,0,0,0,5.0,100,Mobile
1,2,MH00002,Rohan,Maharashtra,Male,54,4,600,163508.11,1,...,1,3,1,62000.0,0,0,0,10.0,150,Mobile
2,3,KA00003,Ananya,Karnataka,Female,58,1,724,138773.12,1,...,1,3,1,97000.0,0,0,0,5.0,100,Mobile
3,4,MH00004,Nandini,Maharashtra,Female,39,2,695,136048.53,1,...,0,1,1,157000.0,0,0,0,10.0,150,Email
4,5,WB00005,Charvi,West Bengal,Female,25,3,675,27798.19,0,...,0,0,1,146000.0,0,0,0,6.0,110,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,KA14996,Vaishnavi,Karnataka,Female,25,3,669,0.00,1,...,1,3,1,138000.0,0,0,0,6.0,110,Email
14996,14997,MH14997,Varsha,Maharashtra,Female,49,2,768,193069.04,1,...,0,2,1,76000.0,0,1,2,4.0,90,Branch
14997,14998,KA14998,Deepak,Karnataka,Male,69,2,600,0.00,1,...,0,1,0,74000.0,1,1,9,3.0,12,Branch
14998,14999,WB14999,Anirudh,West Bengal,Male,53,8,793,100747.75,0,...,0,1,1,120000.0,0,1,19,4.0,2,Mobile
14999,15000,DL15000,Jhanvi,Delhi,Female,42,6,663,10280.30,1,...,0,1,1,147000.0,0,0,0,7.0,120,Phone

In [35]:
df.columns = df.columns.str.replace(' ','_').str.replace(' ','')
df

,rownumber,customerid,first_name,state,gender,age,tenure,creditscore,balance,hascrcard,...,hasfd,numofproducts,isactivemember,salary,exited,complain,numcomplain,satisfaction_score,point_earned,preferredchannel
0,1,TN00001,Sunita,Tamil Nadu,Female,26,1,673,117822.37,1,...,1,2,1,62000.0,0,0,0,5.0,100,Mobile
1,2,MH00002,Rohan,Maharashtra,Male,54,4,600,163508.11,1,...,1,3,1,62000.0,0,0,0,10.0,150,Mobile
2,3,KA00003,Ananya,Karnataka,Female,58,1,724,138773.12,1,...,1,3,1,97000.0,0,0,0,5.0,100,Mobile
3,4,MH00004,Nandini,Maharashtra,Female,39,2,695,136048.53,1,...,0,1,1,157000.0,0,0,0,10.0,150,Email
4,5,WB00005,Charvi,West Bengal,Female,25,3,675,27798.19,0,...,0,0,1,146000.0,0,0,0,6.0,110,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,KA14996,Vaishnavi,Karnataka,Female,25,3,669,0.00,1,...,1,3,1,138000.0,0,0,0,6.0,110,Email
14996,14997,MH14997,Varsha,Maharashtra,Female,49,2,768,193069.04,1,...,0,2,1,76000.0,0,1,2,4.0,90,Branch
14997,14998,KA14998,Deepak,Karnataka,Male,69,2,600,0.00,1,...,0,1,0,74000.0,1,1,9,3.0,12,Branch
14998,14999,WB14999,Anirudh,West Bengal,Male,53,8,793,100747.75,0,...,0,1,1,120000.0,0,1,19,4.0,2,Mobile
14999,15000,DL15000,Jhanvi,Delhi,Female,42,6,663,10280.30,1,...,0,1,1,147000.0,0,0,0,7.0,120,Phone

✅ Step 3: Handle Missing Values

Check for missing values in the dataset.

Impute or drop based on the type of column:

Salary: Replace missing values with the median.

Balance: Replace missing values with 0 (assume no balance).

Satisfaction Score: Fill missing values with median.

Gender: Drop rows with missing values.

Card Type: Fill with the most frequent value (mode).

📌 Hint: Use .fillna(), .dropna(), .median(), .mode().

In [36]:
df.isnull()

,rownumber,customerid,first_name,state,gender,age,tenure,creditscore,balance,hascrcard,...,hasfd,numofproducts,isactivemember,salary,exited,complain,numcomplain,satisfaction_score,point_earned,preferredchannel
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [37]:
df.isnull().sum()

rownumber              0
customerid             0
first_name             0
state                  0
gender                 0
age                    0
tenure                 0
creditscore            0
balance                9
hascrcard              0
card_type              8
hasloan                0
hasfd                  0
numofproducts          0
isactivemember         0
salary                12
exited                 0
complain               0
numcomplain            0
satisfaction_score     8
point_earned           0
preferredchannel       0
dtype: int64

In [38]:
df.shape #to know the shape

(14984, 22)

df.dropna will remove all the rows we have na

In [39]:
df = df.dropna(subset=['gender'])

we can findout more values

In [40]:
df[df['gender'] == 'Male']

,rownumber,customerid,first_name,state,gender,age,tenure,creditscore,balance,hascrcard,...,hasfd,numofproducts,isactivemember,salary,exited,complain,numcomplain,satisfaction_score,point_earned,preferredchannel
1,2,MH00002,Rohan,Maharashtra,Male,54,4,600,163508.11,1,...,1,3,1,62000.0,0,0,0,10.0,150,Mobile
5,6,KA00006,Ritik,Karnataka,Male,48,3,600,181554.57,1,...,0,1,1,102000.0,0,0,0,8.0,130,Mobile
6,7,WB00007,Yash,West Bengal,Male,44,5,736,238171.06,1,...,1,3,1,55000.0,0,0,0,8.0,130,Mobile
7,8,DL00008,Ishaan,Delhi,Male,26,8,659,220844.13,1,...,0,2,1,53000.0,0,1,4,7.0,120,Mobile
10,11,MH00011,Nikhil,Maharashtra,Male,51,6,664,14429.73,0,...,0,1,1,75000.0,0,0,0,10.0,150,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14989,14990,TN14990,Yash,Tamil Nadu,Male,28,7,646,232779.48,1,...,0,1,1,95000.0,0,0,0,5.0,100,Phone
14992,14993,KA14993,Arvind,Karnataka,Male,26,3,693,67476.15,1,...,1,2,1,57000.0,0,0,0,6.0,110,Mobile
14994,14995,DL14995,Ashok,Delhi,Male,50,2,702,88428.59,1,...,1,2,1,38000.0,0,1,11,4.0,18,Mobile
14997,14998,KA14998,Deepak,Karnataka,Male,69,2,600,0.00,1,...,0,1,0,74000.0,1,1,9,3.0,12,Branch
14998,14999,WB14999,Anirudh,West Bengal,Male,53,8,793,100747.75,0,...,0,1,1,120000.0,0,1,19,4.0,2,Mobile

we have option called ### fillna that fills somthing you want

In [41]:
df['gender'] = df['gender'].fillna('Unknown')

In [42]:
df.shape

(14984, 22)

In [48]:
mid = df['salary'].median()

In [49]:
df['salary'] = df['salary'].fillna(mid)

In [50]:
df.isnull().sum()

rownumber             0
customerid            0
first_name            0
state                 0
gender                0
age                   0
tenure                0
creditscore           0
balance               9
hascrcard             0
card_type             8
hasloan               0
hasfd                 0
numofproducts         0
isactivemember        0
salary                0
exited                0
complain              0
numcomplain           0
satisfaction_score    8
point_earned          0
preferredchannel      0
dtype: int64